version: "3"

services:
  postgres:
    image: postgres:10-alpine
    volumes:
      - growler-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-growler}
    restart: unless-stopped

volumes:
  growler-pgdata:
