export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const GET_GROWLS_SUCCESS = 'GET_GROWLS_SUCCESS';
export const CREATE_GROWL_SUCCESS = 'CREATE_GROWL_SUCCESS';
export const DELETE_GROWL_SUCCESS = 'DELETE_GROWL_SUCCESS';
export const RESET_GROWL_CREATION_SUCCESS = 'RESET_GROWL_CREATION_SUCCESS';
